---
abstract: 'Event-based multi-process supervisor'
author:
  - 'Gelu Lupaş <gvl@cpan.org>'
  - 'Pedro Melo <melo@simplicidade.org>'
build_requires:
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132660'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Sv
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::Sv:
    file: lib/App/Sv.pm
    version: 0.013
  App::Sv::Command:
    file: lib/App/Sv/Command.pm
  App::Sv::Log:
    file: lib/App/Sv/Log.pm
  App::Sv::Socket:
    file: lib/App/Sv/Socket.pm
  App::Sv::Util:
    file: lib/App/Sv/Util.pm
recommends:
  Async::Interrupt: 0
  EV: 0
  Guard: 0
requires:
  AnyEvent: 6.01
  Carp: 0
  POSIX: 0
  YAML::Tiny: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/ggl/App-Sv/issues
  homepage: https://github.com/ggl/App-Sv
  repository: https://github.com/ggl/App-Sv.git
version: 0.013
x_authority: cpan:GVL
