name = "App-Sv"
authors = ['Gelu Lupas <gelu@devnull.ro>', 'Pedro Melo <melo@simplicidade.org>']
authority = "cpan:GVL"
license = "artistic_2"
readme_from = "lib/App/Sv.pm"
abstract_from = "lib/App/Sv.pm"
